interface SchemaTreePath {
    isAutoGenerated: boolean;
    parts: string[];
}

interface ReaderOptions {
    logLevelKey: SchemaTreePath | null;
    timestampKey: SchemaTreePath | null;
    utcOffsetKey: SchemaTreePath | null;
}


export type {
    ReaderOptions,
    SchemaTreePath,
};
