import fs from "node:fs";
import path from "node:path";
import {pipeline} from "node:stream/promises";
import {fileURLToPath} from "node:url";

import axios from "axios";

import MainModuleFactory, {
    type ClpStreamReader,
    type MainModule,
} from "../dist/ClpFfiJs-node.js";
import {
    DECODE_CHUNK_SIZE,
    FILTERED_CHUNK_SIZE,
    LOG_LEVEL_ERROR,
    LOG_LEVEL_INFO,
    LOG_LEVEL_WARN,
    OUT_OF_BOUNDS_OFFSET,
} from "./constants.js";


const TEST_DATA_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "data");

/**
 * Downloads a file from a URL to a local path if it doesn't already exist.
 *
 * @param url The URL to download from.
 * @param filePath The local file path to save to.
 */
const downloadFileIfNeeded = async (url: string, filePath: string): Promise<void> => {
    if (fs.existsSync(filePath)) {
        return;
    }

    fs.mkdirSync(path.dirname(filePath), {recursive: true});

    const response = await axios.get(url, {responseType: "stream"});
    await pipeline(response.data, fs.createWriteStream(filePath));
};

/**
 * Loads a test data file as a Uint8Array, downloading it from S3 if it doesn't exist locally.
 *
 * @param filename The name of the file in the test data directory.
 * @return The file contents as a Uint8Array.
 */
const loadTestData = async (filename: string): Promise<Uint8Array> => {
    const filePath = path.join(TEST_DATA_DIR, filename);

    const urlMap: Record<string, string> = {
        "cockroachdb.clp.zst": "https://yscope.s3.us-east-2.amazonaws.com/sample-logs/cockroachdb.clp.zst",
        "yarn-unstructured.clp.zst": "https://yscope.s3.us-east-2.amazonaws.com/sample-logs/yarn-ubuntu-resourcemanager-ip-172-31-17-135.log.1.clp.zst",
    };

    const url = urlMap[filename];
    if ("undefined" === typeof url) {
        throw new Error(`Unknown test data file: ${filename}`);
    }

    await downloadFileIfNeeded(url, filePath);

    return new Uint8Array(fs.readFileSync(filePath));
};

/**
 * Creates a new WASM module instance.
 *
 * @return A promise that resolves to the MainModule instance.
 */
const createModule = async (): Promise<MainModule> => {
    // eslint-disable-next-line new-cap
    return MainModuleFactory();
};

interface SchemaTreePath {
    isAutoGenerated: boolean;
    parts: string[];
}

interface ReaderOptions {
    logLevelKey: SchemaTreePath | null;
    timestampKey: SchemaTreePath | null;
    utcOffsetKey: SchemaTreePath | null;
}

const DEFAULT_READER_OPTIONS: ReaderOptions = {
    logLevelKey: null,
    timestampKey: null,
    utcOffsetKey: null,
};

/**
 * Creates a ClpStreamReader with the given options.
 *
 * @param module The WASM module instance.
 * @param data The IR stream data.
 * @param options Reader options for key extraction. Defaults to null for all keys.
 * @return A new ClpStreamReader instance.
 */
const createReader = (
    module: MainModule,
    data: Uint8Array,
    options: ReaderOptions = DEFAULT_READER_OPTIONS
): ClpStreamReader => {
    return new module.ClpStreamReader(data, options);
};


export type {
    ClpStreamReader,
    MainModule,
    ReaderOptions,
};
export {
    createModule,
    createReader,
    DECODE_CHUNK_SIZE,
    FILTERED_CHUNK_SIZE,
    loadTestData,
    LOG_LEVEL_ERROR,
    LOG_LEVEL_INFO,
    LOG_LEVEL_WARN,
    OUT_OF_BOUNDS_OFFSET,
};
