import {expect} from "vitest";

import type {
    ClpStreamReader,
    MainModule,
} from "../dist/ClpFfiJs-node.js";


interface SchemaTreePath {
    isAutoGenerated: boolean;
    parts: string[];
}

interface ReaderOptions {
    logLevelKey: SchemaTreePath | null;
    timestampKey: SchemaTreePath | null;
    utcOffsetKey: SchemaTreePath | null;
}

const DEFAULT_READER_OPTIONS: ReaderOptions = {
    logLevelKey: null,
    timestampKey: null,
    utcOffsetKey: null,
};

const TEST_DATA_DIR = "test/data";


/**
 * Asserts that a value is not null or undefined, narrowing the type for later usage.
 *
 * @param val
 */
const assertNonNull: <T>(val: T) => asserts val is NonNullable<T> = (val) => {
    expect(val).not.toBeNull();
};


/**
 * Detects whether the current runtime is Node.js.
 *
 * @return True if running in Node.js.
 */
const isNodeRuntime = (): boolean => {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
    return "undefined" !== typeof process && "string" === typeof process.versions?.node;
};

/**
 * Creates a new WASM module instance, using the Node.js build when running in Node.js
 * and the worker/browser build otherwise.
 *
 * @return A promise that resolves to the MainModule instance.
 */
const createModule = async (): Promise<MainModule> => {
    if (true === isNodeRuntime()) {
        const {default: factory} =
            // eslint-disable-next-line no-inline-comments
            await import(/* @vite-ignore */ "../dist/ClpFfiJs-node.js");

        return factory();
    }
    const {default: factory} = await import("../dist/ClpFfiJs-worker.js");

    return factory();
};

/**
 * Creates a ClpStreamReader with the given options.
 *
 * @param module The WASM module instance.
 * @param data The IR stream data.
 * @param options Reader options for key extraction. Defaults to null for all keys.
 * @return A new ClpStreamReader instance.
 */
const createReader = (
    module: MainModule,
    data: Uint8Array,
    options: ReaderOptions = DEFAULT_READER_OPTIONS
): ClpStreamReader => {
    return new module.ClpStreamReader(data, options);
};

/**
 * Reads a file from the test data directory using Node.js APIs.
 *
 * @param filename The name of the file in the test data directory.
 * @return The file contents as a Uint8Array.
 */
const readNodeFile = async (filename: string): Promise<Uint8Array> => {
    const fs =
        // eslint-disable-next-line no-inline-comments
        await import(/* @vite-ignore */ "node:fs");
    const path =
        // eslint-disable-next-line no-inline-comments
        await import(/* @vite-ignore */ "node:path");
    const {fileURLToPath} =
        // eslint-disable-next-line no-inline-comments
        await import(/* @vite-ignore */ "node:url");

    const filePath = path.join(
        path.dirname(fileURLToPath(import.meta.url)),
        "data",
        filename
    );

    return new Uint8Array(fs.readFileSync(filePath));
};

/**
 * Loads a test data file as a Uint8Array. Test data is pre-downloaded by `globalSetup.ts`.
 * In Node.js, files are read from disk. In browser, files are served by Vite's dev server.
 *
 * @param filename The name of the file in the test data directory.
 * @return The file contents as a Uint8Array.
 */
const loadTestData = async (filename: string): Promise<Uint8Array> => {
    if (true === isNodeRuntime()) {
        return readNodeFile(filename);
    }

    const response = await fetch(`/${TEST_DATA_DIR}/${filename}`);

    return new Uint8Array(await response.arrayBuffer());
};


export type {
    ClpStreamReader,
    MainModule,
    ReaderOptions,
};
export {
    assertNonNull,
    createModule,
    createReader,
    loadTestData,
};
