import {expect} from "vitest";

import type {
    ClpStreamReader,
    MainModule,
} from "../../dist/ClpFfiJs-node.js";


interface SchemaTreePath {
    isAutoGenerated: boolean;
    parts: string[];
}

interface ReaderOptions {
    logLevelKey: SchemaTreePath | null;
    timestampKey: SchemaTreePath | null;
    utcOffsetKey: SchemaTreePath | null;
}

const DEFAULT_READER_OPTIONS: ReaderOptions = {
    logLevelKey: null,
    timestampKey: null,
    utcOffsetKey: null,
};

const TEST_DATA_URLS: Readonly<Record<string, string>> = {
    "structured-cockroachdb.clp.zst": "https://yscope.s3.us-east-2.amazonaws.com/sample-logs/cockroachdb.clp.zst",
    "unstructured-yarn.clp.zst": "https://yscope.s3.us-east-2.amazonaws.com/sample-logs/yarn-ubuntu-resourcemanager-ip-172-31-17-135.log.1.clp.zst",
};

/**
 * Creates a ClpStreamReader with the given options.
 *
 * @param module The WASM module instance.
 * @param data The IR stream data.
 * @param options Reader options for key extraction. Defaults to null for all keys.
 * @return A new ClpStreamReader instance.
 */
const createReader = (
    module: MainModule,
    data: Uint8Array,
    options: ReaderOptions = DEFAULT_READER_OPTIONS
): ClpStreamReader => {
    return new module.ClpStreamReader(data, options);
};


/**
 * Asserts that a value is not null or undefined, narrowing the type for later usage.
 *
 * @param val
 */
const assertNonNull: <T>(val: T) => asserts val is NonNullable<T> = (val) => {
    expect(val).not.toBeNull();
};


export type {
    ClpStreamReader,
    MainModule,
    ReaderOptions,
};
export {
    assertNonNull,
    createReader,
    TEST_DATA_URLS,
};
