name: "docs"

on:
  pull_request:
    paths: &monitored_paths
      - ".github/workflows/docs.yaml"
      - "package-lock.json"
      - "package.json"
      - "src/**/*.ts"
      - "taskfile.yaml"
      - "taskfiles/docs.yaml"
      - "typedoc.jsonc"
  push:
    paths: *monitored_paths
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  docs:
    permissions:
      contents: "read"
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-24.04"]
    runs-on: "${{matrix.os}}"
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"  # v6.0.2
        with:
          submodules: "recursive"

      - name: "Install task"
        run: "npm install -g @go-task/cli@3.48.0"

      - if: "matrix.os == 'macos-latest'"
        name: "Install coreutils (for md5sum)"
        run: "brew install coreutils"

      - name: "Build docs"
        run: "task docs:build"

      - if: >-
          contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name)
          && 'ubuntu-24.04' == matrix.os
        name: "Upload docs artifact"
        uses: "actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa"  # v3.0.1
        with:
          name: "docs"
          path: "build/docs"
          if-no-files-found: "error"

          # Retain the artifact for a week in case there was a deployment issue
          retention-days: 7

  deploy:
    if: >-
      contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name)
    needs: ["docs"]
    permissions:
      contents: "read"
      # Required by actions/deploy-pages for OIDC authentication.
      id-token: "write"
      # Required to deploy the uploaded artifact to GitHub Pages.
      pages: "write"
    runs-on: "ubuntu-24.04"
    environment:
      name: "github-pages"
      url: "${{steps.deployment.outputs.page_url}}"
    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e"  # v4.0.5
