name: "tests"

on:
  pull_request:
    paths: &monitored_paths
      - ".github/workflows/test.yaml"
      - "CMakeLists.txt"
      - "package-lock.json"
      - "package.json"
      - "src/**"
      - "taskfile.yaml"
      - "taskfiles/**"
      - "test/**"
      - "tools/yscope-dev-utils"
      - "tsconfig.json"
      - "vitest.config.ts"
  push:
    paths: *monitored_paths
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  tests:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"  # v6.0.2
        with:
          submodules: "recursive"

      - uses: "./tools/yscope-dev-utils/exports/github/actions/install-go-task"

      - uses: "./tools/yscope-dev-utils/exports/github/actions/print-tool-versions"

      - name: "Run JS tests"
        run: "task test:js"
